# Generated by Django 3.2.4 on 2021-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/users/logobackingwhite.png', upload_to='users/avatars/'),
        ),
    ]
