# Generated by Django 3.2.4 on 2021-07-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_to_carousel',
            field=models.BooleanField(default=False, help_text='Check this box to add this post to the homepage carousel. Carousel will only hold 5 slides.'),
        ),
    ]
