# Generated by Django 3.2.4 on 2021-07-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_add_to_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_to_carousel',
            field=models.BooleanField(default=False, help_text='<small style="color:teal">Field accepts all uppercase only</small>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10),
        ),
    ]
