# Generated by Django 3.2.4 on 2021-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210728_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_to_carousel',
            field=models.BooleanField(default=True, help_text='<small style="color: #222222; font-weight: 300; font-size: 13px;">Check this box to add this post to the carousel. <span style="color: red">Carousel will only hold 5 slides</span></small>'),
        ),
    ]
