# Generated by Django 3.2.4 on 2021-07-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_to_carousel',
            field=models.CharField(choices=[('add_to_carousel', 'Yes'), ('remove_from_carousel', 'No')], default='add_to_carousel', help_text='<small style="color: #222222; opacity: 0.5; font-weight: 300; font-size: 13px;">Uncheck this box to remove this post from the carousel. <span style="color: red">Carousel will only hold 5 slides</span></small>', max_length=20),
        ),
    ]
