# Generated by Django 3.2.4 on 2021-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210729_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_to_carousel',
            field=models.CharField(choices=[('remove_from_carousel', 'No'), ('add_to_carousel', 'Yes')], default='remove_from_carousel', help_text='<small style="color: red; opacity: 0.5; font-weight: 300; font-size: 13px;">Carousel limited to 5 posts.</small>', max_length=20),
        ),
    ]
