# Generated by Django 3.2.4 on 2021-07-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0002_auto_20210727_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitestyling',
            name='styling_name',
            field=models.TextField(default='Styling name'),
        ),
    ]
