# Generated by Django 3.2.4 on 2021-07-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0003_globalsitestyling_styling_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsitestyling',
            name='styling_name',
            field=models.CharField(default='Styling name', max_length=100),
        ),
    ]
